### ISSUE TITLE
Use SVGElementIter

### ISSUE THREAD

**Issue by sammycage** [donRumata03/Painter#2]
https://github.com/donRumata03/Painter/blob/71fbc049d9a7da25ed1626b8d3c6eefa9b2aa2cc/vector_graphics/SVG_service.cpp#L28-L42

``` cpp

#include "svgelementiter.h" 

... 

SVGElementIter it(root, "", "path");
while(it. next() ) 
{
    lunasvg::SVGElement* path = it.currentElement();

    // Your code here
} 

... 

```

**Comment by donRumata03** [comment]
Thanks for such a caring support!
We'll definitely modernize this soon.

**Comment by donRumata03** [comment]
Thanks for your reply, the enhancement is performed in: https://github.com/donRumata03/Painter/commit/2e3ffbfe07f1e6e627372202c969d6907aa3200b
